### ISSUE TITLE
Updating the app deletes notes

### ISSUE THREAD

**Issue by 18qs** [SimpleMobileTools/Simple-Notes#100] opened 2017-07-10 13:59 UTC
This is incredibly painful and inconvenient. I updated the app via F-Droid on my LG G4, and my entire stored note was gone. The last backup was an extended period of time ago so much data has been lost

**Comment by trubitsyn** [comment] 2017-07-10 15:16
That has not happenned to me yet. Looks like a regression was introduced in one of the previous versions. Could you tell which version had you had installed before you updated the app?

**Comment by smichel17** [comment] 2017-07-10 16:11
It happened to me a while ago. I did not lose all my notes. IIRC there was no obvious connection between which notes were lost and which were saved.

**Comment by tibbi** [comment] 2017-07-10 16:53
weird... Have you been rotating the device by any chance? Or you just backgrounded or exited it, then after  restarting everything was deleted? Was it only the notes content deleted, or whole notes?

**Comment by tibbi** [comment] 2017-07-10 17:00
or have you exported the notes in a file, maybe used import? I need some more info for fixing it. Thanks

**Comment by smichel17** [comment] 2017-07-10 17:27
Went back and looked at emails and was able to find out some more information.

- [confident] I lost my notes during an upgrade.
  - [positive] The upgrade happened between March 30th and April 12th, 2017
- [positive] One of the notes I lost was created on March 30th.
  - [confident] I usually update frequently, so I'm pretty sure I was running the latest (v2.1.1). That would mean the loss happened in the upgrade from v2.1.1 to v2.1.2.
- [positive] A note I had created many months earlier was not lost.
- [not confident] The contents of the general note were lost.
- [very not confident] The contents of the March 30th note were lost but the note itself was not deleted.

**Comment by trubitsyn** [comment] 2017-07-10 18:00
@tibbi I'm trying to find out whether updating any earlier version to current reproduces the bug. I'll let you know when I finish.

**Comment by tibbi** [comment] 2017-07-10 18:32
there used to be some issue if clickable links were enabled, that should be fixed already. Ill release a new version soon with some fixed crashes, I dont really see how could upgrading the app delete notes. Maybe it will fix itself and wont happen to new users already :)

**Comment by trubitsyn** [comment] 2017-07-10 18:35
There are no clickable links in earlier versions. It's clearly a regression :(

**Comment by tibbi** [comment] 2017-07-10 18:36
by reproducing you mean its 100% happening? If you upgrade from 1.6 to 2.0+ the note is always lost?

**Comment by trubitsyn** [comment] 2017-07-10 18:39
Always. All I do is simply type something, press save button (note gets saved, I double checked). Then I install the update, open the app, note is lost.

**Comment by tibbi** [comment] 2017-07-10 19:13
Ok thanks for testing. Not sure what do you actually mean by 1.4 etc, the old version were from 1.0 to 1.24, then 2.0. Ive tried upgrading from 1.24 to 2.0 or to the latest one, couldnt reproduce the issue. Doesnt really look like its still an issue, maybe there was a glitch in some cases.

**Comment by trubitsyn** [comment] 2017-07-10 19:13
@tibbi here's what I've found:

**1.0 - 1.3 -> 1.4 and later** deletes note content (1.x allow to create only one note)
1.4 -> 1.6 not reproducible
**1.4 - 1.9 -> 2.0.0 and later** reproducible
2.0.0...2.2.3 (consequent updates) not reproducible

@18qs wrote:

> my entire stored **note** was gone

I think @18qs used to use either **1.0 - 1.3** or **1.4 - 1.9** before update.

**Comment by trubitsyn** [comment] 2017-07-10 19:14
> Not sure what do you actually mean by 1.4 etc

I used git tags. Are versions different?

**Comment by tibbi** [comment] 2017-07-10 19:20
ok no problem, anyway it looks like its not really relevant anymore. Ill release a new version today and see if someone still reports it, thanks

**Comment by trubitsyn** [comment] 2017-07-10 19:22
You could mention 1.x is deprecated somewhere in readme. Even better, if you restrict updating 1.x to 2.x then people will not be confused.

**Comment by tibbi** [comment] 2017-07-10 19:42
the last 1.x was released in december when I barely had any users, its just not worth spending much time with

**Comment by 18qs** [comment] 2017-07-10 21:23
The version of the app I was using was quite old - possibly a 2016 version. It did not support more than 1 note, so I can assume it was a 1.x version. Probably my fault for not updating sooner.

**Comment by tibbi** [comment] 2017-09-23 09:20
this might be invalid already

**Closed by tibbi** 2017-09-23 09:20 UTC
Labels: bug
