### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by tonverstagen** [SimpleMobileTools/Simple-Notes#154] opened 2018-01-18 22:39 UTC
Hello,

I noted that this app has an English UI on my Dutch Android system. I'm a native Dutch speaker and I'd love to translate the necessary strings for you. Is this possible? I didn't find anything about translations on Github or your webpage.

Kind regards,

Ton Verstagen

**Comment by trubitsyn** [comment] 2018-01-18 23:21
Hello, Tom! Please see https://github.com/SimpleMobileTools/General-Discussion/blob/master/README.md#how-can-i-suggest-an-edit-to-a-file for a detailed information.

**Comment by smichel17** [comment] 2018-01-19 01:31
There's also an app called stringlate which helps automate this process: https://github.com/LonamiWebs/Stringlate

**Comment by tibbi** [comment] 2018-01-19 08:05
Hey, it should already be translated in dutch at https://github.com/SimpleMobileTools/Simple-Notes/blob/master/app/src/main/res/values-nl/strings.xml , everything is in english for you? Maybe you have a different dialect of dutch, if more of them exist?

**Comment by tonverstagen** [comment] 2018-01-20 08:52
Very strange. After a reinstall from the play store, to my surprise I found out it was localized indeed!
Sorry for starting an issue for nothing.
I do however have one more remark. I still wanted to make a (very minor) change in a string to update the language. However, upon when I try to change the file with the strings, my only given option is to start a whole new fork of the project and make the change in there. Does this mean the language file  is locked?

**Comment by tonverstagen** [comment] 2018-01-20 09:20
I think I just found a bug. This could also explain my confusion about the app not being localized in my language. Will try to report it thoroughly:

Bug name: **Localized language does not come back after reverting "Use English language" switch in settings**
System: Android 7.1.2, Dutch locale
Description: After installing Simple Notes from the play store on my Dutch Android OS, the UI of the app is fully Dutch.
After opening the settings and clicking the switch to "Use English language", the name of the app in the app drawer is still in Dutch (and in the settings menu I still see the Dutch word for "settings" as title of the menu in the top (which is maybe even some different bug?)), but at least the remaining UI is English.
**When I revert the switch "Use English language", however, the UI keeps being in English, instead of going back to Dutch.**

Hope I explained it clearly enough.
Thank you for supporting so far.

**Comment by trubitsyn** [comment] 2018-01-20 12:03
@tibbi referencing https://github.com/SimpleMobileTools/Simple-File-Manager/issues/156. The issue is in Commons.

**Comment by tibbi** [comment] 2018-01-20 12:32
the language should be toggled fine if you kill it by swiping away the app from Recents, I will try improving it.

**Comment by tibbi** [comment] 2018-01-20 12:32
anyway thats a different issue affecting all apps so Ill close this issue

**Closed by tibbi** 2018-01-20 12:32 UTC

**Comment by smichel17** [comment] 2018-01-20 13:55
Android has some caching behavior where it keeps the process around in memory even though it is closed, for faster startup if you open it again. It is possible to force Android to clear the cache, by enabling developer options on your phone and then poking around in there, but the easier way to do it, if you don't plan on doing it often, is to reboot your phone.

**Comment by tibbi** [comment] 2018-01-20 14:08
the language should be set properly if you just murder the app by swiping it away from recents, exiting it with the back button just isnt enough.

**Comment by smichel17** [comment] 2018-01-20 15:20
When changing the locale specifically (not in this app), I've had to make sure it is gone from Settings > Developer options > Running services > Cached processes as well.

**Comment by tibbi** [comment] 2018-01-20 15:25
and I just tested toggling the language, it worked fine even after restarting the app with back button only, didnt even have to swipe it away. Guess it's just another thing that depends on both Android OS version and the device manufacturer too.

**Comment by smichel17** [comment] 2018-01-20 15:32
Yeah. Might also depend on whether the other language is RTL.
