### ISSUE TITLE
Sharing web link to app corrupts target note

### ISSUE THREAD

**Issue by Danoloan10** [SimpleMobileTools/Simple-Notes#311] opened 2019-12-01 17:44 UTC
When sharing a web link through Simple-Notes, the target note gets corrupted and opening it crashes the application. The application crashes even when the note shows in the tabs upper row,  not even needed to open it. Because of this, I cannot delete the corrupted notes, as to delete them I would have to open them first; and cannot open the notes next to the corrupted.

**Comment by tibbi** [comment] 2019-12-01 18:24
What app version are you using? I mean what number is at the bottom of the About section.

**Comment by Danoloan10** [comment] 2019-12-01 18:25
version 6.2.1

**Comment by tibbi** [comment] 2019-12-01 18:50
how exactly could I reproduce it?

**Comment by Danoloan10** [comment] 2019-12-01 23:12
open a browser  or some app that shares links through the share android utility and share it to notes. I have had this problem sharing videos with NewPipe and web pages with Lightning to the Notes app

**Comment by Danoloan10** [comment] 2019-12-03 13:58
thanks for the effort. meanwhile, is there any way i can remove these corrupted notes from outside the app, so I can continue using the app normally

**Comment by tibbi** [comment] 2019-12-03 14:56
I dont think there is. You can create note widgets and see your current notes there to avoid losing them, then reinstall the app I guess. Or just wait for the next version, not sure when will it be released though.

**Comment by tibbi** [comment] 2019-12-07 11:40
I cannot reproduce it. Havent you tried sharing a video itself in the note, and it crashes just because of the size? Do you have "Make links and emails clickable" enabled in the app settings?

**Comment by Danoloan10** [comment] 2019-12-07 12:24
ok, now I can't reproduce it either, but the app keeps crashing when the note I made this issue for appears on the screen, even when its just the title in the top bar. Could it be something related to the title? The note is called "r"

**Comment by tibbi** [comment] 2019-12-07 12:58
What is in the note? Couldnt it be too big?

**Comment by Danoloan10** [comment] 2019-12-07 13:01
it was a new note that i created to copy the link I shared through NewPipe, so I can't know what's in the note

**Comment by tibbi** [comment] 2019-12-08 19:10
I still cant reproduce it, nor I see a reason why would it be crashing. Try clearing your app data from the device settings, just to see you reset everything (it will clear your notes too). Do you have the "Make links and emails clickable" setting enabled?

**Comment by Danoloan10** [comment] 2019-12-17 13:42
I could export all the notes to .txt. I can see the note with which the app crashes, and it has the youtube link. the file of the name is fine too. however the app kept crashing as before. After importing all notes again to a clean install, it correctly shows the problematic note. No clue what could have happened.

As a side note, checking this I have seen that the .txt files do not include a newline character at the end. It may be a good idea to include it to ease the command line inspection of the files.

**Comment by tibbi** [comment] 2020-02-25 09:00
does the crash happen to any link, or it contains some special characters? Could you give us the .txt file with the crashing note? If we can reproduce it, we can fix it too. Thanks

**Comment by Danoloan10** [comment] 2020-03-14 19:44
[r.txt](https://github.com/SimpleMobileTools/Simple-Notes/files/4333272/r.txt)

This is it. As of today, I have not had the same problem again.

**Comment by tibbi** [comment] 2020-03-15 01:24
ok thanks, it should be fixed already indeed.

**Closed by tibbi** 2020-03-15 01:24 UTC
Labels: bug
