### ISSUE TITLE
Checklist sharing not working properly

### ISSUE THREAD

**Issue by bhoomi0104** [SimpleMobileTools/Simple-Notes#694] opened 2023-09-30 16:44 UTC
There is an issue with checklist sharing feature in the repository.

Checklist share functionality does not share a list of items, but object details instead. 

When I create a checklist and share it, the app shares the following result rather than the actual content:

`[{"dateCreated":1696091464923,"id":1,"isDone":false,"title":"Check1"},{"dateCreated":1696091464923,"id":2,"isDone":false,"title":"Check2"},{"dateCreated":1696091464923,"id":3,"isDone":true,"title":"Check3"},{"dateCreated":1696091464923,"id":4,"isDone":true,"title":"Check4"},{"dateCreated":1696091464923,"id":5,"isDone":false,"title":"Check5"}]`

**Comment by Aga-C** [comment] 2023-09-30 16:50
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Notes/issues/533.

**Comment by bhoomi0104** [comment] 2023-09-30 16:56
Ok sorry but it's feature request and I think this is a bug!

**Closed** 2023-09-30 18:37 UTC
