### ISSUE TITLE
Pressing "next" or "previous" button goes to next URL, not next character

### ISSUE THREAD

**Issue by genodeftest** [SimpleMobileTools/Simple-Notes#178] opened 2018-02-26 18:42 UTC
Steps to reproduce:
0. have any keyboard with arrow buttons, e.g. AnySoftKeyboard with a top bar.
1. open any note containing several URLs and a few lines of text.
2. in the note, place the cursor to any text.
3. press the arrow button

what happens:
Cursor jumps to previous/next URL

What is expected to happen:
Cursor should go to previous/next character as in regular caret navigation.

Affected version:
3.1.1 installed from f-droid.
Phone is running Android 8.0.0 with security updates from februar.

**Comment by tibbi** [comment] 2018-02-26 18:52
duplicate of #136 . I tried reproducing it already, but it always worked fine in my cases

**Closed by tibbi** 2018-02-26 18:52 UTC
