### ISSUE TITLE
Large Notes Delete Text At The End Of Note

### ISSUE THREAD

**Issue by GTHub23** [SimpleMobileTools/Simple-Notes#276] opened 2019-03-27 13:21 UTC
**Background**
Recently I noticed that one of my larger notes was missing a few words on the last few lines, and one word was missing a few characters. Upon further investigation, I also found that the exported version of the note suffered the same issue, both when it is exported as a standalone .txt file, and when the note updates the .txt file directly. I've noticed that when the character counter is enabled, once a note reaches 1570 characters it stops counting, or only counts the next dozen or so characters as as 1 or 2 extra; i.e. the counter only goes from 1570 to 1571/1572 instead of 1580 for instance

**Steps To Reproduce**
1. Create a note
2. Add text up to 1570 characters
3. Add 5 characters to the note (bringing the total to 1575)
4a. _If Auto-Save enable_: swipe to another note to save, and/or export the note to .txt
4b: _If Auto-Save not enable_: click save, and/or export the note to .txt
5: Exit the app
6: Re-open the app at the note in question

**What Should Happen**
The extra 5+ characters added in Step 3 should be added to both the in-app note and the exported note
Furthermore, the character counter should update to reflect the new character count of 1575

**What Actually Happens**
Prior to saving/exproting the character counter only updates to show 1571 or 1572 characters despite having 1575 characters entered in Step 2
These extra 5 characters are then seemingly automatically deleted without user interaction (except to save/export the note), and both the in-app note and the exported note are truncated down to the 1570 character count
_No other text is deleted during this process either through user interaction or by the app_

**Examples**
_Note_: all but text relevant has been redacted for privacy purposes. This is simply to show an example of whats happening

_Text Entered_
http://i1189.photobucket.com/albums/z425/Geode-010/Screenshot_20190327-132305%20Blurred.png

_Post-Save/Export_
http://i1189.photobucket.com/albums/z425/Geode-010/Screenshot_20190327-132325%20Blurred.png

**Comment by GTHub23** [comment] 2019-03-29 13:33
**Update**
I've just gone back in and checked my notes and found something else that is probably related
I export my files to an external SD Card (64GB SanDisk card with ~30GB free) and I've noticed a few others also have problems exporting regardless of how many characters they have. The vast majority are fine, just the odd couple

I have tested a new fix which at least partially works. Using the above note of 1570 characters which I have listed below

**Steps To Reproduce**
1. Copy text from an affected note
2. Paste into a new note
3. Fill in missing text and save the note (either with autosave or tapping the save icon)
4. Export the _file content only_

**What Should Happen**
Both the note contained within Simple Notes and the exported text file should contain exactly the same text

**What Actually Happens**
The note contained within Simple Notes is unaffected, but the exported note drops the last few characters

**Notes**
As noted previously, the longest note suffering from this issue is ~1570 characters, whereas the shortest note to suffer <=100 characters (give or take), so my assumption is that character count is not the issue but more likely a storage/database issue(?); not my area of expertise mind, just a thought

**Comment by GTHub23** [comment] 2019-05-25 02:24
**Update**
Still having problems with some notes deleting text when exported/saved to SD card, butI think I've narrowed down the problem. As opposed to being too long, it seems that only notes that include a Unicode character seem to be affected.

Here is what I did:

**Steps To Reproduce**

1. Create a new note
2. Insert dummy text with standard English letters and/or punctuation (A-Z, a-z, 0-9, etc)
3. Export to file and allow for automatic updating
4. Insert special (non-English) character (e.g. ø is one I've tested)
5. Save the file

**What Should Happen**
Both the note contained within Simple Notes and the exported text file should contain exactly the same text

**What Actually Happens**
The note contained within Simple Notes is and the exported note drops the last character or characters (depending on how many special characters are added)

**Notes**
Hopefully this helps in finally squashing this bug for good

**Comment by tibbi** [comment] 2019-05-25 15:16
what app version do you have?

**Comment by GTHub23** [comment] 2019-05-27 01:32
Im currently using the following app and Android versions:

- Simple Notes Pro: v6.1.3
- Android: 7.1.1

**Comment by tibbi** [comment] 2019-09-16 20:12
should be fixed in 6.2.0 released soon, it was caused by some special characters that occupy more than one byte

**Closed by tibbi** 2019-09-16 20:12 UTC
Labels: bug
