### ISSUE TITLE
[Feature request] Notes encryption

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Notes#1] opened 2016-07-09 02:39 UTC

**Comment by user6529576559** [comment] 2017-08-24 14:00
Use Androids's built in encryption feature which encrypts the internal storage and the SD card too. Set password for unlocking your phone. This way if the phone is stolen or you lose it your data won't be exposed to others.

Do not borrow your phone, buy a new phone for the other person instead. It would be possible that you get back it with full of hardware and software backdoors installed on it. If you have secrets on your phone, don't even give it out from your hands.

This feature request would be useful though in cases when the attacker forces you to tell the screen lock password. It is not very likely that the attacker will sweep through all the apps and check if one of them has additional password protection (like Signal privacy messenger). If it is just a simple robbery. If it is not, you are fucked anyways. Seek for assistance immediately if you are living in an abusive relationship.

**Comment by tibbi** [comment] 2020-09-26 15:01
duplicate of #365

**Closed by tibbi** 2020-09-26 15:01 UTC
Labels: feature request
