### ISSUE TITLE
(feature request) Allow User Control Of Sorting/Grouping

### ISSUE THREAD

**Issue by puppykickr** [SimpleMobileTools/Simple-Notes#312] opened 2019-12-07 20:54 UTC
Great app, very useful and easy to use.
I feel it may be made a bit better if the user had control over how the notes were ordered, just like we do in your Gallery and File Manager.

And of course, the same options to sort and group that the other apps use would be ideal.

This would streamline the app for those of us that have many notes, and notes of different types.

I am hoping to use the app for song lyrics, along with any other notepad functions.

As it would be cumbersome to sort through many notes of lyrics to get to a shopping list or some other temporary note, you can see how sorting and grouping could be rather helpful.

**Comment by tibbi** [comment] 2019-12-08 09:18
duplicate of #83

**Closed by tibbi** 2019-12-08 09:18 UTC
