### ISSUE TITLE
Sync notes with syncml server

### ISSUE THREAD

**Issue by Magissia** [SimpleMobileTools/Simple-Notes#8] opened 2016-07-21 19:36 UTC
Hello,. it would be useful to be able to sync notes with syncml server

**Comment by smichel17** [comment] 2016-12-14 19:20
Close this as a duplicate of #38, which covers this as a more general case?

**Comment by mueller-ma** [comment] 2016-12-14 20:01
I think we can close this and add the syncml server to #38

**Closed** 2016-12-14 20:22 UTC
Labels: feature request
