### ISSUE TITLE
App ends when trying to start

### ISSUE THREAD

**Issue by Foxdelmar** [SimpleMobileTools/Simple-Notes#57] opened 2016-12-23 18:19 UTC
Hi,
thanks for your app. I really like a functional open source app with such a simplicity.

I used an older version  and updated it to the second latest version (1.22) that was offered in the F-Droid repo.
Unfortunately I could not start the app anymore. During the start it showed 
""Notes" was ended", and I could only tap on "send report" or "OK".

After updating to the published version 1.24 the same problem occured.
I was only able to export the data using Titanium Backup.

Do you have any clue why this error may have occured?
Could you keep this in mind for further updates?

Best regards
Fox

**Comment by smichel17** [comment] 2016-12-23 20:00
I wonder if this is the same as #46

**Comment by Foxdelmar** [comment] 2016-12-23 21:57
yeah, sorry. same issue then #46.

**Comment by tibbi** [comment] 2016-12-24 12:03
duplicate of #46

**Closed by tibbi** 2016-12-24 12:03 UTC
