### ISSUE TITLE
[Feature Request] Notebooks and password locking

### ISSUE THREAD

**Issue by ctnkyaumt** [SimpleMobileTools/Simple-Notes#696] opened 2023-10-07 09:41 UTC
I searched to see if anyone else had opened any similar requests. It would be excellent if we could categorize notes by creating notebooks. They could be like buttons like notebooks with their spirals to make them look like actual notebooks. I drew what I meant [here](https://ibb.co/yd4JW3t) Also, It would be a great extra to be able to lock them with a password.

**Comment by Aga-C** [comment] 2023-10-07 11:15
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Notes/issues/158.

**Comment by inson1** [comment] 2023-10-07 11:26
Yes Its duplicate, just edit it for feature request on top of #158 for password option for sub organization imho. Or someone is going to close it for duplicate.

**Closed** 2023-10-07 16:46 UTC
