### ISSUE TITLE
Text gets cut on widget

### ISSUE THREAD

**Issue by herou** [SimpleMobileTools/Simple-Notes#284] opened 2019-06-17 13:48 UTC
![Screenshot_20190617-153935_Samsung Experience Home](https://user-images.githubusercontent.com/13895430/59608755-556c9c00-9116-11e9-93ed-d5e8caec6c40.jpg)

While playing with the widget I realized that if I set the minimum width the text gets cut.

**Comment by tibbi** [comment] 2019-06-17 14:46
you mean setting minimum width in the code, or what?

**Comment by herou** [comment] 2019-06-17 14:51
> you mean setting minimum width in the code, or what?
Not in code. After I showed the widget on screen I was playing with the size of the widget.

**Comment by herou** [comment] 2019-06-17 15:22
I think we should increase the minimum size of the widget width.

**Comment by tibbi** [comment] 2019-06-17 19:23
it works just fine to me, I cannot reproduce it. Increasing widget width is not related to the issue at all.

**Comment by herou** [comment] 2019-06-17 19:24
I can make a screen recording if you wish.

**Comment by tibbi** [comment] 2019-06-17 21:34
well maybe it will help, we will see

**Comment by herou** [comment] 2019-06-18 14:36
Here you have the screen recording: https://drive.google.com/file/d/1gWx5fS2NCAMZLzMq2xqdjMGPKO9NfmeD/view
Sorry for the rumors on the background.
Hope you find this video useful.

**Comment by tibbi** [comment] 2019-07-24 20:50
should be fixed in 6.1.5

**Closed by tibbi** 2019-07-24 20:50 UTC
Labels: bug
