### ISSUE TITLE
default location for new files

### ISSUE THREAD

**Issue by protoloo** [SimpleMobileTools/Simple-Notes#134] opened 2017-11-03 10:39 UTC
Please, add a default location for the option "export as a file"

**Comment by smichel17** [comment] 2017-11-03 17:07
I believe it's possible to save to `$STORAGE/Android/data/com.simplemobiletools.notes/files/` without requesting file system permissions.

I have not spent much time researching this; I discovered it when I saw that [DNS66](https://github.com/julian-klode/dns66/) is able to download files to the equivalent location, without being granted the file system permission. I'm not sure how stable/reliable this is as a storage space. It might be called the cache?

If it turns out to be an appropriate place to store files, can I suggest backing *all* notes with a file and using this as the default location?

**Comment by loziniak** [comment] 2017-12-18 13:31
Maybe default location could be the last location used. Maybe no additional option is necessary in config.

**Comment by tibbi** [comment] 2017-12-18 13:51
Ill actually mark this as a duplicate of #148 , that's a better solution. I dont want to use any temporary cache files for these things.

**Closed by tibbi** 2017-12-18 13:51 UTC
Labels: feature request

**Comment by smichel17** [comment] 2017-12-18 20:26
I'm actually doubting that it's is called the cache. When I look at an app's details view in my settings, files in this folder show up as 'data'. You can delete them by pressing 'clear data', but that would also delete any notes in the app, so it seems like this folder is at least as persistent as internal app data. For example, osmAnd~ stores its map files in its equivalent directory.

I still think this solution makes sense in *addition* to #148, because it allows syncing notes without granting the file system permission.

Or I could create a new issue that's specifically focused on that aspect of it. Or not at all, if you're not interested.

**Comment by tibbi** [comment] 2017-12-18 20:54
It might be some internal storage of the app, but I still dont want to save there. That folder belongs to the app so if you uninstall it, the file will very most likely be deleted too. The goal of exporting to a file is to safely export to an easily accessible file, not somewhere deep in the system. Requesting the storage permission at exporting to a file is expected, nobody should be wondering what's going on.

**Comment by smichel17** [comment] 2017-12-19 01:02
I would *totally* appreciate all new notes automatically creating a file in a certain folder that I can sync to my nextcloud.

**Comment by smichel17** [comment] 2017-12-19 01:04
It makes everything so much simpler from a UX perspective, too. You don't need to worry about exported vs internal exported notes, everything is just a text file and the internal files live in the app's internal storage.

**Comment by smichel17** [comment] 2017-12-27 13:43
You can get the location of this with `Context.getFilesDir()`

https://developer.android.com/reference/android/content/Context.html#getFilesDir()

https://developer.android.com/training/data-storage/files.html#WriteInternalStorage

**Comment by tibbi** [comment] 2017-12-27 14:22
I dont want to change it for now, it doesnt have enough added value

**Comment by smichel17** [comment] 2017-12-27 14:57
Would you accept a PR?

**Comment by tibbi** [comment] 2017-12-27 15:14
probably not, I dont see the benefit of it
