### ISSUE TITLE
[Feature Request] Markdown preview should be first

### ISSUE THREAD

**Issue by konju1** [SimpleMobileTools/Simple-Notes#525] opened 2022-04-24 09:43 UTC
It would be great if Markdown preview is the first thing you see.
On iOS app if you open your note, the first thing you se is markdown formatted text. 
Swipe to the left, and you see preview. 
Reversed would be great, which means if you open up your note you see markdown preview, and if you wish to edit markdown then swipe to the left. 

The same thing on web and desktop app. 
Or at least implement some setting to do such thing. Thanks

**Comment by tibbi** [comment] 2022-04-24 10:42
duplicate of #188

**Closed by tibbi** 2022-04-24 10:42 UTC
